#ifndef AUDIO_CONFIG_H
#define AUDIO_CONFIG_H

#define NUM_CHANNELS					 2
#define AUDIO_DATA_SIZE                 24
#define AUDIO_SAMPLE_RATE               96
#define AUDIO_BUFFER_SAMPLES_PER_CHANNEL 16

#if AUDIO_DATA_SIZE == 24
#define AUDIO_BUFFER_T int32_t
#define AUDIO_BUFFER_16BIT_LENGTH AUDIO_BUFFER_SAMPLES_PER_CHANNEL << (NUM_CHANNELS)
#define AUDIO_BUFFER_LENGTH AUDIO_BUFFER_16BIT_LENGTH >> 1 // should treat length as int32
#else
#define AUDIO_BUFFER_T int16_t
#define AUDIO_BUFFER_16BIT_LENGTH (AUDIO_BUFFER_SAMPLES_PER_CHANNEL << (NUM_CHANNELS - 1))
#define AUDIO_BUFFER_LENGTH AUDIO_BUFFER_16BIT_LENGTH
#endif

#define AUDIO_BUFFER_PTR_T AUDIO_BUFFER_T*

#endif
