#ifndef I2S_AUDIO_SETTINGS_H
#define I2S_AUDIO_SETTINGS_H

#include "stm32f7xx_hal.h"

#define NUM_CHANNELS					 2
#define AUDIO_DATA_SIZE                 24
#define AUDIO_SAMPLE_RATE               44
#define AUDIO_BUFFER_SAMPLES_PER_CHANNEL 1

#if AUDIO_DATA_SIZE == 24
#define I2S_DATAFORMAT I2S_DATAFORMAT_24B
#define AUDIO_BUFFER_T int32_t
#define AUDIO_BUFFER_16BIT_LENGTH AUDIO_BUFFER_SAMPLES_PER_CHANNEL << (NUM_CHANNELS)
#define AUDIO_BUFFER_LENGTH AUDIO_BUFFER_16BIT_LENGTH >> 1 // should treat lenght as int32
#else
#define I2S_DATAFORMAT I2S_DATAFORMAT_16B
#define AUDIO_BUFFER_T int16_t
#define AUDIO_BUFFER_16BIT_LENGTH AUDIO_BUFFER_SAMPLES_PER_CHANNEL << (NUM_CHANNELS - 1)
#define AUDIO_BUFFER_LENGTH AUDIO_BUFFER_16BIT_LENGTH
#endif

#define AUDIO_BUFFER_PTR_T AUDIO_BUFFER_T*

// TODO: extend
#if AUDIO_SAMPLE_RATE == 44
#define I2S_SAMPLE_RATE I2S_AUDIOFREQ_44K
#else
#define I2S_SAMPLE_RATE I2S_AUDIOFREQ_96K
#endif

#endif
